### ISSUE TITLE
Error in 2018-01-08.json

### ISSUE THREAD

**Issue by scottpham** [alexlitel/congresstweets#5]
Hi, the first entry in the [`2018-01-08.json`](https://github.com/alexlitel/congresstweets/blob/master/data/2018-01-08.json) file is a single open bracket `"["`. Its hard to tell if this suggests that some data is missing here or if there was simply a parsing error or what. Do you know what might have caused this and whether data might be missing in that spot?

**Comment by alexlitel** [comment]
Thanks for catching this. My guess it has something to do with the way the app serializes the current day's tweets when I manually push user datasets with new accounts (I added accounts for Tina Smith and Doug Jones that day). There was a bug with the post-build process where it didn't properly create queries to collect tweets. Hopefully this shouldn't come up.

I'll run a script and check if there were any missing tweets that day, as well as try to add any tweets that were missing (need to retroactively add Smith and Jones tweets too).

**Comment by alexlitel** [comment]
After running a script data file went from something around 750kb to 1.3mb, so a number of tweets were definitely missing. Issue also occurred on 12-15 when I added John Curtis' accounts (alas, I don't have access to premium Twitter APIs so I can't try to rebuild that dataset).
